-module(tcp_server_test).
-include_lib("eunit/include/eunit.hrl").

response_test() ->
    A = "GET / HTTP/1.0\r\nAccept: text/html\r\nHost: localhost:1234\r\nUser-Agent: ApacheBench/2.3\r\n\r\n",
    B = "POST / HTTP/1.0\r\nAccept: application/json\r\nHost: localhost:1234\r\nUser-Agent: ApacheBench/2.3\r\n\r\n",
    C = "DELETE / HTTP/1.0\r\nAccept: text/html\r\nHost: localhost:1234\r\nUser-Agent: ApacheBench/2.3\r\n\r\n",
    D = "GET / HTTP/1.0\r\nAccept: wrong_type\r\nHost: localhost:1234\r\nUser-Agent: ApacheBench/2.3\r\n\r\n",
    E = "CHECK / HTTP/1.0\r\nAccept: text/html\r\nHost: localhost:1234\r\nUser-Agent: ApacheBench/2.3\r\n\r\n",
    F = "CHECK / HTTP/1.0\r\nHost: localhost\r\nAccept: text/html\r\nUser-Agent: ApacheBench/2.3\r\n\r\n",
    A_length = term_to_binary(byte_size(<<"<div> <span>method:</span> <span>GET</span> </div>\r\n\r\n">>)),
    A_answer = <<"HTTP/1.1 200 OK\r\nContent-Type: text/html\r\nContent-Length: ", 
                A_length/binary,
                "\r\n\r\n<div> <span>method:</span> <span>GET</span> </div>\r\n\r\n">>,
    B_length = term_to_binary(byte_size(<<"{'method':'POST'}\r\n\r\n">>)),
    B_answer = <<"HTTP/1.1 201 Created\r\nContent-Type: application/json\r\nContent-Length: ", 
                B_length/binary,
                "\r\n\r\n{'method':'POST'}\r\n\r\n">>,
    C_length = term_to_binary(byte_size(<<"<div> <span>method:</span> <span>DELETE</span> </div>\r\n\r\n">>)),
    C_answer = <<"HTTP/1.1 204 No content\r\nContent-Type: text/html\r\nContent-Length: ", 
                C_length/binary,
                "\r\n\r\n<div> <span>method:</span> <span>DELETE</span> </div>\r\n\r\n">>,
    D_length = term_to_binary(byte_size(<<"ERROR\r\n\r\n">>)),
    D_answer = <<"HTTP/1.1 400 Bad Request\r\nContent-Type: wrong content-type\r\nContent-Length: ", 
                D_length/binary,
                "\r\n\r\nERROR\r\n\r\n">>,
    E_length = term_to_binary(byte_size(<<"<div> <span>method:</span> <span>CHECK</span> </div>\r\n\r\n">>)),
    E_answer = <<"HTTP/1.1 501 Not Implemented\r\nContent-Type: text/html\r\nContent-Length: ", 
                E_length/binary, 
                "\r\n\r\n<div> <span>method:</span> <span>CHECK</span> </div>\r\n\r\n">>,
    F_length = term_to_binary(byte_size(<<"<div> <span>method:</span> <span>CHECK</span> </div>\r\n\r\n">>)),
    F_answer = <<"HTTP/1.1 501 Not Implemented\r\nContent-Type: text/html\r\nContent-Length: ", 
                F_length/binary, 
                "\r\n\r\n<div> <span>method:</span> <span>CHECK</span> </div>\r\n\r\n">>,
    ?assertEqual(A_answer, tcp_client_example:send_request(A)),
    ?assertEqual(B_answer, tcp_client_example:send_request(B)),
    ?assertEqual(C_answer, tcp_client_example:send_request(C)),
    ?assertEqual(D_answer, tcp_client_example:send_request(D)),
    ?assertEqual(E_answer, tcp_client_example:send_request(E)),
    ?assertEqual(F_answer, tcp_client_example:send_request(F)),
    ok.